name: Deploy HTML to s3 

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read  

on: push 
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::612117410675:role/github-role
            aws-region: us-east-1

      - name: Code static s3
        run: |
            aws s3 sync . s3://alpha-beta-demo-jhashist --exclude "*"  --include "index.html"
